---

version: '2.2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    build:
      context: .
      network: detnode
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "32181:32181"

  kafka:
    image: confluentinc/cp-kafka:latest
    build:
      context: .
      network: detnode
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "29092:29092"
